// Generated by gencpp from file stonefish_mvp/Int32Stamped.msg
// DO NOT EDIT!


#ifndef STONEFISH_MVP_MESSAGE_INT32STAMPED_H
#define STONEFISH_MVP_MESSAGE_INT32STAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stonefish_mvp
{
template <class ContainerAllocator>
struct Int32Stamped_
{
  typedef Int32Stamped_<ContainerAllocator> Type;

  Int32Stamped_()
    : header()
    , data(0)  {
    }
  Int32Stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> const> ConstPtr;

}; // struct Int32Stamped_

typedef ::stonefish_mvp::Int32Stamped_<std::allocator<void> > Int32Stamped;

typedef boost::shared_ptr< ::stonefish_mvp::Int32Stamped > Int32StampedPtr;
typedef boost::shared_ptr< ::stonefish_mvp::Int32Stamped const> Int32StampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_mvp::Int32Stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_mvp::Int32Stamped_<ContainerAllocator1> & lhs, const ::stonefish_mvp::Int32Stamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_mvp::Int32Stamped_<ContainerAllocator1> & lhs, const ::stonefish_mvp::Int32Stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_mvp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7344a45486eefa24d2f337265df37ce";
  }

  static const char* value(const ::stonefish_mvp::Int32Stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7344a45486eefa2ULL;
  static const uint64_t static_value2 = 0x4d2f337265df37ceULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_mvp/Int32Stamped";
  }

  static const char* value(const ::stonefish_mvp::Int32Stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stonefish_mvp::Int32Stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int32Stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_mvp::Int32Stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_mvp::Int32Stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_MVP_MESSAGE_INT32STAMPED_H
