// Generated by gencpp from file stonefish_mvp/SonarSettings.msg
// DO NOT EDIT!


#ifndef STONEFISH_MVP_MESSAGE_SONARSETTINGS_H
#define STONEFISH_MVP_MESSAGE_SONARSETTINGS_H

#include <ros/service_traits.h>


#include <stonefish_mvp/SonarSettingsRequest.h>
#include <stonefish_mvp/SonarSettingsResponse.h>


namespace stonefish_mvp
{

struct SonarSettings
{

typedef SonarSettingsRequest Request;
typedef SonarSettingsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SonarSettings
} // namespace stonefish_mvp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stonefish_mvp::SonarSettings > {
  static const char* value()
  {
    return "3dd7b67bb9c281a0e1f972514667dae6";
  }

  static const char* value(const ::stonefish_mvp::SonarSettings&) { return value(); }
};

template<>
struct DataType< ::stonefish_mvp::SonarSettings > {
  static const char* value()
  {
    return "stonefish_mvp/SonarSettings";
  }

  static const char* value(const ::stonefish_mvp::SonarSettings&) { return value(); }
};


// service_traits::MD5Sum< ::stonefish_mvp::SonarSettingsRequest> should match
// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings >
template<>
struct MD5Sum< ::stonefish_mvp::SonarSettingsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_mvp::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettingsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_mvp::SonarSettingsRequest> should match
// service_traits::DataType< ::stonefish_mvp::SonarSettings >
template<>
struct DataType< ::stonefish_mvp::SonarSettingsRequest>
{
  static const char* value()
  {
    return DataType< ::stonefish_mvp::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettingsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stonefish_mvp::SonarSettingsResponse> should match
// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings >
template<>
struct MD5Sum< ::stonefish_mvp::SonarSettingsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_mvp::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettingsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_mvp::SonarSettingsResponse> should match
// service_traits::DataType< ::stonefish_mvp::SonarSettings >
template<>
struct DataType< ::stonefish_mvp::SonarSettingsResponse>
{
  static const char* value()
  {
    return DataType< ::stonefish_mvp::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettingsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STONEFISH_MVP_MESSAGE_SONARSETTINGS_H
