// Generated by gencpp from file stonefish_mvp/SonarSettings2.msg
// DO NOT EDIT!


#ifndef STONEFISH_MVP_MESSAGE_SONARSETTINGS2_H
#define STONEFISH_MVP_MESSAGE_SONARSETTINGS2_H

#include <ros/service_traits.h>


#include <stonefish_mvp/SonarSettings2Request.h>
#include <stonefish_mvp/SonarSettings2Response.h>


namespace stonefish_mvp
{

struct SonarSettings2
{

typedef SonarSettings2Request Request;
typedef SonarSettings2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SonarSettings2
} // namespace stonefish_mvp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stonefish_mvp::SonarSettings2 > {
  static const char* value()
  {
    return "77368ba160f8f6dd31453146bbd4b728";
  }

  static const char* value(const ::stonefish_mvp::SonarSettings2&) { return value(); }
};

template<>
struct DataType< ::stonefish_mvp::SonarSettings2 > {
  static const char* value()
  {
    return "stonefish_mvp/SonarSettings2";
  }

  static const char* value(const ::stonefish_mvp::SonarSettings2&) { return value(); }
};


// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings2Request> should match
// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings2 >
template<>
struct MD5Sum< ::stonefish_mvp::SonarSettings2Request>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_mvp::SonarSettings2 >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettings2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_mvp::SonarSettings2Request> should match
// service_traits::DataType< ::stonefish_mvp::SonarSettings2 >
template<>
struct DataType< ::stonefish_mvp::SonarSettings2Request>
{
  static const char* value()
  {
    return DataType< ::stonefish_mvp::SonarSettings2 >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettings2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings2Response> should match
// service_traits::MD5Sum< ::stonefish_mvp::SonarSettings2 >
template<>
struct MD5Sum< ::stonefish_mvp::SonarSettings2Response>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_mvp::SonarSettings2 >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettings2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_mvp::SonarSettings2Response> should match
// service_traits::DataType< ::stonefish_mvp::SonarSettings2 >
template<>
struct DataType< ::stonefish_mvp::SonarSettings2Response>
{
  static const char* value()
  {
    return DataType< ::stonefish_mvp::SonarSettings2 >::value();
  }
  static const char* value(const ::stonefish_mvp::SonarSettings2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STONEFISH_MVP_MESSAGE_SONARSETTINGS2_H
