// Generated by gencpp from file stonefish_mvp/ThrusterState.msg
// DO NOT EDIT!


#ifndef STONEFISH_MVP_MESSAGE_THRUSTERSTATE_H
#define STONEFISH_MVP_MESSAGE_THRUSTERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stonefish_mvp
{
template <class ContainerAllocator>
struct ThrusterState_
{
  typedef ThrusterState_<ContainerAllocator> Type;

  ThrusterState_()
    : header()
    , setpoint()
    , rpm()
    , thrust()
    , torque()  {
    }
  ThrusterState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , setpoint(_alloc)
    , rpm(_alloc)
    , thrust(_alloc)
    , torque(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _setpoint_type;
  _setpoint_type setpoint;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _rpm_type;
  _rpm_type rpm;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _thrust_type;
  _thrust_type thrust;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::stonefish_mvp::ThrusterState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_mvp::ThrusterState_<ContainerAllocator> const> ConstPtr;

}; // struct ThrusterState_

typedef ::stonefish_mvp::ThrusterState_<std::allocator<void> > ThrusterState;

typedef boost::shared_ptr< ::stonefish_mvp::ThrusterState > ThrusterStatePtr;
typedef boost::shared_ptr< ::stonefish_mvp::ThrusterState const> ThrusterStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_mvp::ThrusterState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_mvp::ThrusterState_<ContainerAllocator1> & lhs, const ::stonefish_mvp::ThrusterState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.setpoint == rhs.setpoint &&
    lhs.rpm == rhs.rpm &&
    lhs.thrust == rhs.thrust &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_mvp::ThrusterState_<ContainerAllocator1> & lhs, const ::stonefish_mvp::ThrusterState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_mvp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_mvp::ThrusterState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_mvp::ThrusterState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_mvp::ThrusterState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93e0b03a2fe79ac1fe95ccde2413a6a6";
  }

  static const char* value(const ::stonefish_mvp::ThrusterState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93e0b03a2fe79ac1ULL;
  static const uint64_t static_value2 = 0xfe95ccde2413a6a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_mvp/ThrusterState";
  }

  static const char* value(const ::stonefish_mvp::ThrusterState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] setpoint\n"
"float64[] rpm\n"
"float64[] thrust\n"
"float64[] torque\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stonefish_mvp::ThrusterState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.setpoint);
      stream.next(m.rpm);
      stream.next(m.thrust);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrusterState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_mvp::ThrusterState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_mvp::ThrusterState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "setpoint[]" << std::endl;
    for (size_t i = 0; i < v.setpoint.size(); ++i)
    {
      s << indent << "  setpoint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.setpoint[i]);
    }
    s << indent << "rpm[]" << std::endl;
    for (size_t i = 0; i < v.rpm.size(); ++i)
    {
      s << indent << "  rpm[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rpm[i]);
    }
    s << indent << "thrust[]" << std::endl;
    for (size_t i = 0; i < v.thrust.size(); ++i)
    {
      s << indent << "  thrust[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.thrust[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.torque[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_MVP_MESSAGE_THRUSTERSTATE_H
