// Generated by gencpp from file mvp_msgs/ChangeState.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_CHANGESTATE_H
#define MVP_MSGS_MESSAGE_CHANGESTATE_H

#include <ros/service_traits.h>


#include <mvp_msgs/ChangeStateRequest.h>
#include <mvp_msgs/ChangeStateResponse.h>


namespace mvp_msgs
{

struct ChangeState
{

typedef ChangeStateRequest Request;
typedef ChangeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeState
} // namespace mvp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_msgs::ChangeState > {
  static const char* value()
  {
    return "6fc3cc8eedce7a52d2a746bc3e0301b9";
  }

  static const char* value(const ::mvp_msgs::ChangeState&) { return value(); }
};

template<>
struct DataType< ::mvp_msgs::ChangeState > {
  static const char* value()
  {
    return "mvp_msgs/ChangeState";
  }

  static const char* value(const ::mvp_msgs::ChangeState&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_msgs::ChangeStateRequest> should match
// service_traits::MD5Sum< ::mvp_msgs::ChangeState >
template<>
struct MD5Sum< ::mvp_msgs::ChangeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::ChangeState >::value();
  }
  static const char* value(const ::mvp_msgs::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::ChangeStateRequest> should match
// service_traits::DataType< ::mvp_msgs::ChangeState >
template<>
struct DataType< ::mvp_msgs::ChangeStateRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::ChangeState >::value();
  }
  static const char* value(const ::mvp_msgs::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_msgs::ChangeStateResponse> should match
// service_traits::MD5Sum< ::mvp_msgs::ChangeState >
template<>
struct MD5Sum< ::mvp_msgs::ChangeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::ChangeState >::value();
  }
  static const char* value(const ::mvp_msgs::ChangeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::ChangeStateResponse> should match
// service_traits::DataType< ::mvp_msgs::ChangeState >
template<>
struct DataType< ::mvp_msgs::ChangeStateResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::ChangeState >::value();
  }
  static const char* value(const ::mvp_msgs::ChangeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_MSGS_MESSAGE_CHANGESTATE_H
