// Generated by gencpp from file mvp_msgs/ControlProcess.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_CONTROLPROCESS_H
#define MVP_MSGS_MESSAGE_CONTROLPROCESS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace mvp_msgs
{
template <class ContainerAllocator>
struct ControlProcess_
{
  typedef ControlProcess_<ContainerAllocator> Type;

  ControlProcess_()
    : header()
    , control_mode()
    , position()
    , orientation()
    , velocity()
    , angular_rate()  {
    }
  ControlProcess_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_mode(_alloc)
    , position(_alloc)
    , orientation(_alloc)
    , velocity(_alloc)
    , angular_rate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _control_mode_type;
  _control_mode_type control_mode;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_rate_type;
  _angular_rate_type angular_rate;





  typedef boost::shared_ptr< ::mvp_msgs::ControlProcess_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::ControlProcess_<ContainerAllocator> const> ConstPtr;

}; // struct ControlProcess_

typedef ::mvp_msgs::ControlProcess_<std::allocator<void> > ControlProcess;

typedef boost::shared_ptr< ::mvp_msgs::ControlProcess > ControlProcessPtr;
typedef boost::shared_ptr< ::mvp_msgs::ControlProcess const> ControlProcessConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::ControlProcess_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::ControlProcess_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::ControlProcess_<ContainerAllocator1> & lhs, const ::mvp_msgs::ControlProcess_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_mode == rhs.control_mode &&
    lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.velocity == rhs.velocity &&
    lhs.angular_rate == rhs.angular_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::ControlProcess_<ContainerAllocator1> & lhs, const ::mvp_msgs::ControlProcess_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::ControlProcess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::ControlProcess_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::ControlProcess_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d69ec8ca792b43bdcc3f18d942377e81";
  }

  static const char* value(const ::mvp_msgs::ControlProcess_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd69ec8ca792b43bdULL;
  static const uint64_t static_value2 = 0xcc3f18d942377e81ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/ControlProcess";
  }

  static const char* value(const ::mvp_msgs::ControlProcess_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"std_msgs/Header header\n"
"string control_mode\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 orientation\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 angular_rate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mvp_msgs::ControlProcess_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_mode);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.velocity);
      stream.next(m.angular_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlProcess_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::ControlProcess_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::ControlProcess_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.control_mode);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "angular_rate: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_CONTROLPROCESS_H
