// Generated by gencpp from file mvp_msgs/GetControlModes.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_GETCONTROLMODES_H
#define MVP_MSGS_MESSAGE_GETCONTROLMODES_H

#include <ros/service_traits.h>


#include <mvp_msgs/GetControlModesRequest.h>
#include <mvp_msgs/GetControlModesResponse.h>


namespace mvp_msgs
{

struct GetControlModes
{

typedef GetControlModesRequest Request;
typedef GetControlModesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetControlModes
} // namespace mvp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_msgs::GetControlModes > {
  static const char* value()
  {
    return "603519323f79819b7761d3e2017e75dd";
  }

  static const char* value(const ::mvp_msgs::GetControlModes&) { return value(); }
};

template<>
struct DataType< ::mvp_msgs::GetControlModes > {
  static const char* value()
  {
    return "mvp_msgs/GetControlModes";
  }

  static const char* value(const ::mvp_msgs::GetControlModes&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_msgs::GetControlModesRequest> should match
// service_traits::MD5Sum< ::mvp_msgs::GetControlModes >
template<>
struct MD5Sum< ::mvp_msgs::GetControlModesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::GetControlModes >::value();
  }
  static const char* value(const ::mvp_msgs::GetControlModesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::GetControlModesRequest> should match
// service_traits::DataType< ::mvp_msgs::GetControlModes >
template<>
struct DataType< ::mvp_msgs::GetControlModesRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::GetControlModes >::value();
  }
  static const char* value(const ::mvp_msgs::GetControlModesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_msgs::GetControlModesResponse> should match
// service_traits::MD5Sum< ::mvp_msgs::GetControlModes >
template<>
struct MD5Sum< ::mvp_msgs::GetControlModesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::GetControlModes >::value();
  }
  static const char* value(const ::mvp_msgs::GetControlModesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::GetControlModesResponse> should match
// service_traits::DataType< ::mvp_msgs::GetControlModes >
template<>
struct DataType< ::mvp_msgs::GetControlModesResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::GetControlModes >::value();
  }
  static const char* value(const ::mvp_msgs::GetControlModesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_MSGS_MESSAGE_GETCONTROLMODES_H
