// Generated by gencpp from file mvp_msgs/GetStateResponse.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_GETSTATERESPONSE_H
#define MVP_MSGS_MESSAGE_GETSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mvp_msgs/HelmState.h>

namespace mvp_msgs
{
template <class ContainerAllocator>
struct GetStateResponse_
{
  typedef GetStateResponse_<ContainerAllocator> Type;

  GetStateResponse_()
    : state()  {
    }
  GetStateResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mvp_msgs::HelmState_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::mvp_msgs::GetStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::GetStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStateResponse_

typedef ::mvp_msgs::GetStateResponse_<std::allocator<void> > GetStateResponse;

typedef boost::shared_ptr< ::mvp_msgs::GetStateResponse > GetStateResponsePtr;
typedef boost::shared_ptr< ::mvp_msgs::GetStateResponse const> GetStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::GetStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::GetStateResponse_<ContainerAllocator1> & lhs, const ::mvp_msgs::GetStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::GetStateResponse_<ContainerAllocator1> & lhs, const ::mvp_msgs::GetStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::GetStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::GetStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::GetStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97d9809d7a5099304244965594ccb424";
  }

  static const char* value(const ::mvp_msgs::GetStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97d9809d7a509930ULL;
  static const uint64_t static_value2 = 0x4244965594ccb424ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/GetStateResponse";
  }

  static const char* value(const ::mvp_msgs::GetStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/HelmState state\n"
"\n"
"================================================================================\n"
"MSG: mvp_msgs/HelmState\n"
"#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"string name\n"
"string mode\n"
"string[] transitions\n"
;
  }

  static const char* value(const ::mvp_msgs::GetStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::GetStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::GetStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::mvp_msgs::HelmState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_GETSTATERESPONSE_H
