// Generated by gencpp from file mvp_msgs/GetState.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_GETSTATE_H
#define MVP_MSGS_MESSAGE_GETSTATE_H

#include <ros/service_traits.h>


#include <mvp_msgs/GetStateRequest.h>
#include <mvp_msgs/GetStateResponse.h>


namespace mvp_msgs
{

struct GetState
{

typedef GetStateRequest Request;
typedef GetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetState
} // namespace mvp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_msgs::GetState > {
  static const char* value()
  {
    return "95826c4c034c53c3f3aa571a5a09f426";
  }

  static const char* value(const ::mvp_msgs::GetState&) { return value(); }
};

template<>
struct DataType< ::mvp_msgs::GetState > {
  static const char* value()
  {
    return "mvp_msgs/GetState";
  }

  static const char* value(const ::mvp_msgs::GetState&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_msgs::GetStateRequest> should match
// service_traits::MD5Sum< ::mvp_msgs::GetState >
template<>
struct MD5Sum< ::mvp_msgs::GetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::GetState >::value();
  }
  static const char* value(const ::mvp_msgs::GetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::GetStateRequest> should match
// service_traits::DataType< ::mvp_msgs::GetState >
template<>
struct DataType< ::mvp_msgs::GetStateRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::GetState >::value();
  }
  static const char* value(const ::mvp_msgs::GetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_msgs::GetStateResponse> should match
// service_traits::MD5Sum< ::mvp_msgs::GetState >
template<>
struct MD5Sum< ::mvp_msgs::GetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::GetState >::value();
  }
  static const char* value(const ::mvp_msgs::GetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::GetStateResponse> should match
// service_traits::DataType< ::mvp_msgs::GetState >
template<>
struct DataType< ::mvp_msgs::GetStateResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::GetState >::value();
  }
  static const char* value(const ::mvp_msgs::GetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_MSGS_MESSAGE_GETSTATE_H
