// Generated by gencpp from file mvp_msgs/HelmStates.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_HELMSTATES_H
#define MVP_MSGS_MESSAGE_HELMSTATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mvp_msgs/HelmState.h>

namespace mvp_msgs
{
template <class ContainerAllocator>
struct HelmStates_
{
  typedef HelmStates_<ContainerAllocator> Type;

  HelmStates_()
    : states()  {
    }
  HelmStates_(const ContainerAllocator& _alloc)
    : states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mvp_msgs::HelmState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mvp_msgs::HelmState_<ContainerAllocator> >> _states_type;
  _states_type states;





  typedef boost::shared_ptr< ::mvp_msgs::HelmStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::HelmStates_<ContainerAllocator> const> ConstPtr;

}; // struct HelmStates_

typedef ::mvp_msgs::HelmStates_<std::allocator<void> > HelmStates;

typedef boost::shared_ptr< ::mvp_msgs::HelmStates > HelmStatesPtr;
typedef boost::shared_ptr< ::mvp_msgs::HelmStates const> HelmStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::HelmStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::HelmStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::HelmStates_<ContainerAllocator1> & lhs, const ::mvp_msgs::HelmStates_<ContainerAllocator2> & rhs)
{
  return lhs.states == rhs.states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::HelmStates_<ContainerAllocator1> & lhs, const ::mvp_msgs::HelmStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::HelmStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::HelmStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::HelmStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::HelmStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::HelmStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::HelmStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::HelmStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fb91daf3e8086897a6eccc9f862d3a8";
  }

  static const char* value(const ::mvp_msgs::HelmStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fb91daf3e808689ULL;
  static const uint64_t static_value2 = 0x7a6eccc9f862d3a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::HelmStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/HelmStates";
  }

  static const char* value(const ::mvp_msgs::HelmStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::HelmStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"mvp_msgs/HelmState[] states\n"
"================================================================================\n"
"MSG: mvp_msgs/HelmState\n"
"#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"string name\n"
"string mode\n"
"string[] transitions\n"
;
  }

  static const char* value(const ::mvp_msgs::HelmStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::HelmStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HelmStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::HelmStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::HelmStates_<ContainerAllocator>& v)
  {
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mvp_msgs::HelmState_<ContainerAllocator> >::stream(s, indent + "    ", v.states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_HELMSTATES_H
