// Generated by gencpp from file mvp_msgs/HelmState.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_HELMSTATE_H
#define MVP_MSGS_MESSAGE_HELMSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mvp_msgs
{
template <class ContainerAllocator>
struct HelmState_
{
  typedef HelmState_<ContainerAllocator> Type;

  HelmState_()
    : name()
    , mode()
    , transitions()  {
    }
  HelmState_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , mode(_alloc)
    , transitions(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _transitions_type;
  _transitions_type transitions;





  typedef boost::shared_ptr< ::mvp_msgs::HelmState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::HelmState_<ContainerAllocator> const> ConstPtr;

}; // struct HelmState_

typedef ::mvp_msgs::HelmState_<std::allocator<void> > HelmState;

typedef boost::shared_ptr< ::mvp_msgs::HelmState > HelmStatePtr;
typedef boost::shared_ptr< ::mvp_msgs::HelmState const> HelmStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::HelmState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::HelmState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::HelmState_<ContainerAllocator1> & lhs, const ::mvp_msgs::HelmState_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.mode == rhs.mode &&
    lhs.transitions == rhs.transitions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::HelmState_<ContainerAllocator1> & lhs, const ::mvp_msgs::HelmState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::HelmState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::HelmState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::HelmState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::HelmState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::HelmState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::HelmState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::HelmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e4258c9f572ade7cc1dee976cfcc66f";
  }

  static const char* value(const ::mvp_msgs::HelmState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e4258c9f572ade7ULL;
  static const uint64_t static_value2 = 0xcc1dee976cfcc66fULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::HelmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/HelmState";
  }

  static const char* value(const ::mvp_msgs::HelmState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::HelmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"string name\n"
"string mode\n"
"string[] transitions\n"
;
  }

  static const char* value(const ::mvp_msgs::HelmState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::HelmState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.mode);
      stream.next(m.transitions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HelmState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::HelmState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::HelmState_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "transitions[]" << std::endl;
    for (size_t i = 0; i < v.transitions.size(); ++i)
    {
      s << indent << "  transitions[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transitions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_HELMSTATE_H
