// Generated by gencpp from file mvp_msgs/PIDgains.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_PIDGAINS_H
#define MVP_MSGS_MESSAGE_PIDGAINS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mvp_msgs
{
template <class ContainerAllocator>
struct PIDgains_
{
  typedef PIDgains_<ContainerAllocator> Type;

  PIDgains_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , k_i_max(0.0)
    , k_i_min(0.0)  {
    }
  PIDgains_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , k_i_max(0.0)
    , k_i_min(0.0)  {
  (void)_alloc;
    }



   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;

   typedef double _k_i_max_type;
  _k_i_max_type k_i_max;

   typedef double _k_i_min_type;
  _k_i_min_type k_i_min;





  typedef boost::shared_ptr< ::mvp_msgs::PIDgains_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::PIDgains_<ContainerAllocator> const> ConstPtr;

}; // struct PIDgains_

typedef ::mvp_msgs::PIDgains_<std::allocator<void> > PIDgains;

typedef boost::shared_ptr< ::mvp_msgs::PIDgains > PIDgainsPtr;
typedef boost::shared_ptr< ::mvp_msgs::PIDgains const> PIDgainsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::PIDgains_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::PIDgains_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::PIDgains_<ContainerAllocator1> & lhs, const ::mvp_msgs::PIDgains_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd &&
    lhs.k_i_max == rhs.k_i_max &&
    lhs.k_i_min == rhs.k_i_min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::PIDgains_<ContainerAllocator1> & lhs, const ::mvp_msgs::PIDgains_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::PIDgains_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::PIDgains_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::PIDgains_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::PIDgains_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::PIDgains_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::PIDgains_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::PIDgains_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64020c6ebba7ed9dc090c3163510a872";
  }

  static const char* value(const ::mvp_msgs::PIDgains_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64020c6ebba7ed9dULL;
  static const uint64_t static_value2 = 0xc090c3163510a872ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::PIDgains_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/PIDgains";
  }

  static const char* value(const ::mvp_msgs::PIDgains_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::PIDgains_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 k_i_max\n"
"float64 k_i_min\n"
;
  }

  static const char* value(const ::mvp_msgs::PIDgains_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::PIDgains_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.k_i_max);
      stream.next(m.k_i_min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDgains_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::PIDgains_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::PIDgains_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
    s << indent << "k_i_max: ";
    Printer<double>::stream(s, indent + "  ", v.k_i_max);
    s << indent << "k_i_min: ";
    Printer<double>::stream(s, indent + "  ", v.k_i_min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_PIDGAINS_H
