// Generated by gencpp from file mvp_msgs/SetControlPoint.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_SETCONTROLPOINT_H
#define MVP_MSGS_MESSAGE_SETCONTROLPOINT_H

#include <ros/service_traits.h>


#include <mvp_msgs/SetControlPointRequest.h>
#include <mvp_msgs/SetControlPointResponse.h>


namespace mvp_msgs
{

struct SetControlPoint
{

typedef SetControlPointRequest Request;
typedef SetControlPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlPoint
} // namespace mvp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_msgs::SetControlPoint > {
  static const char* value()
  {
    return "572b0a2f8f3a00d3d99441cd02e5edb1";
  }

  static const char* value(const ::mvp_msgs::SetControlPoint&) { return value(); }
};

template<>
struct DataType< ::mvp_msgs::SetControlPoint > {
  static const char* value()
  {
    return "mvp_msgs/SetControlPoint";
  }

  static const char* value(const ::mvp_msgs::SetControlPoint&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_msgs::SetControlPointRequest> should match
// service_traits::MD5Sum< ::mvp_msgs::SetControlPoint >
template<>
struct MD5Sum< ::mvp_msgs::SetControlPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::SetControlPoint >::value();
  }
  static const char* value(const ::mvp_msgs::SetControlPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::SetControlPointRequest> should match
// service_traits::DataType< ::mvp_msgs::SetControlPoint >
template<>
struct DataType< ::mvp_msgs::SetControlPointRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::SetControlPoint >::value();
  }
  static const char* value(const ::mvp_msgs::SetControlPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_msgs::SetControlPointResponse> should match
// service_traits::MD5Sum< ::mvp_msgs::SetControlPoint >
template<>
struct MD5Sum< ::mvp_msgs::SetControlPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_msgs::SetControlPoint >::value();
  }
  static const char* value(const ::mvp_msgs::SetControlPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_msgs::SetControlPointResponse> should match
// service_traits::DataType< ::mvp_msgs::SetControlPoint >
template<>
struct DataType< ::mvp_msgs::SetControlPointResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_msgs::SetControlPoint >::value();
  }
  static const char* value(const ::mvp_msgs::SetControlPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_MSGS_MESSAGE_SETCONTROLPOINT_H
