// Generated by gencpp from file mvp_msgs/SetControlPointResponse.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_SETCONTROLPOINTRESPONSE_H
#define MVP_MSGS_MESSAGE_SETCONTROLPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mvp_msgs
{
template <class ContainerAllocator>
struct SetControlPointResponse_
{
  typedef SetControlPointResponse_<ContainerAllocator> Type;

  SetControlPointResponse_()
    {
    }
  SetControlPointResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetControlPointResponse_

typedef ::mvp_msgs::SetControlPointResponse_<std::allocator<void> > SetControlPointResponse;

typedef boost::shared_ptr< ::mvp_msgs::SetControlPointResponse > SetControlPointResponsePtr;
typedef boost::shared_ptr< ::mvp_msgs::SetControlPointResponse const> SetControlPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mvp_msgs::SetControlPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/SetControlPointResponse";
  }

  static const char* value(const ::mvp_msgs::SetControlPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mvp_msgs::SetControlPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetControlPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::SetControlPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mvp_msgs::SetControlPointResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_SETCONTROLPOINTRESPONSE_H
