// Generated by gencpp from file mvp_msgs/SetControlPointRequest.msg
// DO NOT EDIT!


#ifndef MVP_MSGS_MESSAGE_SETCONTROLPOINTREQUEST_H
#define MVP_MSGS_MESSAGE_SETCONTROLPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mvp_msgs/ControlProcess.h>

namespace mvp_msgs
{
template <class ContainerAllocator>
struct SetControlPointRequest_
{
  typedef SetControlPointRequest_<ContainerAllocator> Type;

  SetControlPointRequest_()
    : setpoint()  {
    }
  SetControlPointRequest_(const ContainerAllocator& _alloc)
    : setpoint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mvp_msgs::ControlProcess_<ContainerAllocator>  _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetControlPointRequest_

typedef ::mvp_msgs::SetControlPointRequest_<std::allocator<void> > SetControlPointRequest;

typedef boost::shared_ptr< ::mvp_msgs::SetControlPointRequest > SetControlPointRequestPtr;
typedef boost::shared_ptr< ::mvp_msgs::SetControlPointRequest const> SetControlPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator1> & lhs, const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.setpoint == rhs.setpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator1> & lhs, const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "572b0a2f8f3a00d3d99441cd02e5edb1";
  }

  static const char* value(const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x572b0a2f8f3a00d3ULL;
  static const uint64_t static_value2 = 0xd99441cd02e5edb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_msgs/SetControlPointRequest";
  }

  static const char* value(const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"mvp_msgs/ControlProcess setpoint\n"
"\n"
"================================================================================\n"
"MSG: mvp_msgs/ControlProcess\n"
"#\n"
"#   This file is part of MVP-Mission program.\n"
"#\n"
"#   MVP-Mission is free software: you can redistribute it and/or modify\n"
"#   it under the terms of the GNU General Public License as published by\n"
"#   the Free Software Foundation, either version 3 of the License, or\n"
"#   (at your option) any later version.\n"
"#\n"
"#   MVP-Mission is distributed in the hope that it will be useful,\n"
"#   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"#   GNU General Public License for more details.\n"
"#\n"
"#   You should have received a copy of the GNU General Public License\n"
"#   along with MVP-Mission.  If not, see <https://www.gnu.org/licenses/>.\n"
"#\n"
"#   Author: Emir Cem Gezer\n"
"#   Email: emircem@uri.edu;emircem.gezer@gmail.com\n"
"#   Year: 2022\n"
"#\n"
"#   Copyright (C) 2022 Smart Ocean Systems Laboratory\n"
"#\n"
"\n"
"std_msgs/Header header\n"
"string control_mode\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 orientation\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 angular_rate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetControlPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_msgs::SetControlPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_msgs::SetControlPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    s << std::endl;
    Printer< ::mvp_msgs::ControlProcess_<ContainerAllocator> >::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_MSGS_MESSAGE_SETCONTROLPOINTREQUEST_H
