(cl:defpackage stonefish_mvp-srv
  (:use )
  (:export
   "SONARSETTINGS"
   "<SONARSETTINGS-REQUEST>"
   "SONARSETTINGS-REQUEST"
   "<SONARSETTINGS-RESPONSE>"
   "SONARSETTINGS-RESPONSE"
   "SONARSETTINGS2"
   "<SONARSETTINGS2-REQUEST>"
   "SONARSETTINGS2-REQUEST"
   "<SONARSETTINGS2-RESPONSE>"
   "SONARSETTINGS2-RESPONSE"
  ))

