#define PULSE_WIDTH_MAX 1900
#define PULSE_WIDTH_MIN 1100
#define PULSE_WIDTH_CTR (PULSE_WIDTH_MAX + PULSE_WIDTH_MIN) / 2.0

#define REPORT_PWM_PERIOD 150

//FIX
#define YAW 3
#define PORT_SURGE 7
#define STERN_HEAVE 11
#define BOW_PORT_HEAVE 16
#define BOW_STARBOARD_EAVE 20
#define STARBOARD_SURGE 26