(cl:in-package mvp_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          DOFS-VAL
          DOFS
          PID_X-VAL
          PID_X
          PID_Y-VAL
          PID_Y
          PID_Z-VAL
          PID_Z
          PID_ROLL-VAL
          PID_ROLL
          PID_PITCH-VAL
          PID_PITCH
          PID_YAW-VAL
          PID_YAW
          PID_SURGE-VAL
          PID_SURGE
          PID_SWAY-VAL
          PID_SWAY
          PID_HEAVE-VAL
          PID_HEAVE
          PID_ROLL_RATE-VAL
          PID_ROLL_RATE
          PID_PITCH_RATE-VAL
          PID_PITCH_RATE
          PID_YAW_RATE-VAL
          PID_YAW_RATE
))