# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stonefish_mvp/BeaconInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class BeaconInfo(genpy.Message):
  _md5sum = "f1127716b80995f5b12a8c1f5f98b902"
  _type = "stonefish_mvp/BeaconInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint8 beacon_id
float32 range
float32 azimuth
float32 elevation
geometry_msgs/Point relative_position
geometry_msgs/Quaternion local_orientation
float32 local_depth
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','beacon_id','range','azimuth','elevation','relative_position','local_orientation','local_depth']
  _slot_types = ['std_msgs/Header','uint8','float32','float32','float32','geometry_msgs/Point','geometry_msgs/Quaternion','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,beacon_id,range,azimuth,elevation,relative_position,local_orientation,local_depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BeaconInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.beacon_id is None:
        self.beacon_id = 0
      if self.range is None:
        self.range = 0.
      if self.azimuth is None:
        self.azimuth = 0.
      if self.elevation is None:
        self.elevation = 0.
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.local_orientation is None:
        self.local_orientation = geometry_msgs.msg.Quaternion()
      if self.local_depth is None:
        self.local_depth = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.beacon_id = 0
      self.range = 0.
      self.azimuth = 0.
      self.elevation = 0.
      self.relative_position = geometry_msgs.msg.Point()
      self.local_orientation = geometry_msgs.msg.Quaternion()
      self.local_depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3f7df().pack(_x.beacon_id, _x.range, _x.azimuth, _x.elevation, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.local_orientation.x, _x.local_orientation.y, _x.local_orientation.z, _x.local_orientation.w, _x.local_depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.local_orientation is None:
        self.local_orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 73
      (_x.beacon_id, _x.range, _x.azimuth, _x.elevation, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.local_orientation.x, _x.local_orientation.y, _x.local_orientation.z, _x.local_orientation.w, _x.local_depth,) = _get_struct_B3f7df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3f7df().pack(_x.beacon_id, _x.range, _x.azimuth, _x.elevation, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.local_orientation.x, _x.local_orientation.y, _x.local_orientation.z, _x.local_orientation.w, _x.local_depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.local_orientation is None:
        self.local_orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 73
      (_x.beacon_id, _x.range, _x.azimuth, _x.elevation, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.local_orientation.x, _x.local_orientation.y, _x.local_orientation.z, _x.local_orientation.w, _x.local_depth,) = _get_struct_B3f7df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B3f7df = None
def _get_struct_B3f7df():
    global _struct_B3f7df
    if _struct_B3f7df is None:
        _struct_B3f7df = struct.Struct("<B3f7df")
    return _struct_B3f7df
